# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27b919178471985382b5759bb20babd971ed1ae048d704be6a6fafcaee08cd0ed8c9fe080cd27e3e3c48b3a74ef25288ed27d6f4387e337ac13b141b801078f1

test:
  secret_key_base: 9bfde50064889c94221bc569b12100381494e5e11b9d954b49ba7374bdaa0024efbbb0df27f8589fc03d9332201982d5d47acffc3cc62141bb65db0908268eed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
