# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Service.create! [
	{name: 'FITNESS & GYM'},
	{name: 'WELLNESS & SPA'},
	{name: 'PISCINAS'},
	{name: 'ACTIVIDADES DIRIGIDAS'},
	{name: 'SERVICIOS'},
	{name: 'RESTAURACIÓN'},
]


Sitem.create! [
	{name: 'MUSCULACIÓN', service_id: 1},
	{name: 'PESO LIBRE', service_id: 1},
	{name: 'CARDIO', service_id: 1},
	{name: 'APARATO DE ABDOMINALES', service_id: 1},
	{name: 'BANCOS DE MUSCULACIÓN', service_id: 1},
	{name: 'BICICLETA ELÍPTICA', service_id: 1},
	{name: 'BICICLETA ESTATICA', service_id: 1},
	{name: 'BICICLETA RECLINABLE', service_id: 1},
	{name: 'TRATADORA', service_id: 1},
	{name: 'MULTIESTACIONES DE MUSCULACIÓN', service_id: 1},
	{name: 'MÁQUINAS DE MUSCULACIÓN', service_id: 1},
	{name: 'SPA E HIDROMASAJE', service_id: 2},
	{name: 'BAÑO DE VAPOR', service_id: 2},
	{name: 'CICLO DUCHAS', service_id: 2},
	{name: 'SALA RELAX', service_id: 2},
	{name: 'PISCINA INTEIOR', service_id: 3},
	{name: 'PISCINA EXTERIOR', service_id: 3},
	{name: 'YOGA', service_id: 4},
	{name: 'PILATES', service_id: 4},
	{name: 'AEROBIC', service_id: 4},
	{name: 'SPINNING', service_id: 4},
	{name: 'STEPS', service_id: 4},
	{name: 'BODY PUMP', service_id: 4},
	{name: 'ABDOMINALES', service_id: 4},
	{name: 'AQUA FIT', service_id: 4},
	{name: 'AQUAGYM', service_id: 4},
	{name: 'BODY COMBAT', service_id: 4},
	{name: 'CRODDFIT', service_id: 4},
	{name: 'TAI CHI', service_id: 4},
	{name: 'TONIFICACIÓN', service_id: 4},
	{name: 'DUCHAS', service_id: 5},
	{name: 'TAQUILLAS', service_id: 5},
	{name: 'VESTUARIO', service_id: 5},
	{name: 'TERRAZA', service_id: 5},
	{name: 'MAQUINAS DE VENDING', service_id: 6},	
]

Zone.create! [
	{name: 'REGIÓN METROPOLITANA'},
	{name: 'CIUDADES'},
]

City.create! [
	{name: 'CERRILLOS', :zone_id => 1},
	{name: 'CERRO NAVIA', :zone_id => 1},
	{name: 'EL BOSQUE', :zone_id => 1},
	{name: 'ESTACIÓN CENTRAL', :zone_id => 1},
	{name: 'HUECHURABA', :zone_id => 1},
	{name: 'INDEPENDENCIA', :zone_id => 1},
	{name: 'LA CISTERNA', :zone_id => 1},
	{name: 'LA FLORIDA', :zone_id => 1},
	{name: 'LA GRANJA', :zone_id => 1},
	{name: 'LA PINTANA', :zone_id => 1},
	{name: 'LA REINA', :zone_id => 1},
	{name: 'LAS CONDES', :zone_id => 1},
	{name: 'LO BARNECHEA', :zone_id => 1},
	{name: 'LO ESPEJO', :zone_id => 1},
	{name: 'LO PRADO', :zone_id => 1},
	{name: 'MAIPÚ', :zone_id => 1},
	{name: 'ÑUÑOA', :zone_id => 1},
	{name: 'PADRE HURTADO', :zone_id => 1},
	{name: 'PEDRO AQUIRRE CERDA', :zone_id => 1},
	{name: 'PEÑALOLEN', :zone_id => 1},
	{name: 'PIRQUE', :zone_id => 1},
	{name: 'PROVIDENCIA', :zone_id => 1},
	{name: 'PUDAHUEL', :zone_id => 1},
	{name: 'QUILICURA', :zone_id => 1},
	{name: 'QUINTA NORMAL', :zone_id => 1},
	{name: 'RECOLETA', :zone_id => 1},
	{name: 'RENCA', :zone_id => 1},
	{name: 'SAN BERNARDO', :zone_id => 1},
	{name: 'SAN JUAQUÍN', :zone_id => 1},
	{name: 'SAN MIGUEL', :zone_id => 1},
	{name: 'SAN RAMÓN', :zone_id => 1},
	{name: 'SANTIAGO', :zone_id => 1},
	{name: 'VITACURA', :zone_id => 1},
	{name: 'Iquique', :zone_id => 2},
	{name: 'Antofagasta', :zone_id => 2},
	{name: 'Calama', :zone_id => 2},
	{name: 'Copiapó', :zone_id => 2},
	{name: 'La Serena', :zone_id => 2},
	{name: 'Coquimbo', :zone_id => 2},
	{name: 'Valparaíso', :zone_id => 2},
	{name: 'Viña de mar', :zone_id => 2},
	{name: 'Rancagua', :zone_id => 2},
	{name: 'Talca', :zone_id => 2},
	{name: 'Concepción', :zone_id => 2},
	{name: 'Temuco', :zone_id => 2},
	{name: 'Pucón', :zone_id => 2},
	{name: 'Villarica', :zone_id => 2},
	{name: 'Valdivia', :zone_id => 2},
	{name: 'Osorno', :zone_id => 2},
	{name: 'Puerto Varas', :zone_id => 2},
	{name: 'Puerto Montt', :zone_id => 2},
	{name: 'Coihaique', :zone_id => 2},
	{name: 'Punta Arenas', :zone_id => 2}, 
]
